# Generated by Django 3.1.2 on 2021-01-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210127_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag_specification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(null=True, to='blog.Tag'),
        ),
    ]
