# Generated by Django 3.1.2 on 2021-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210127_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='author_image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
