# Generated by Django 3.1.2 on 2021-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210130_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='author_image_url',
            field=models.TextField(null=True),
        ),
    ]
